development:
  adapter: postgresql
  encoding: unicode
  database: drone_development
  pool: 5
  username: postgres
  password: dz

test:
  adapter: postgresql
  encoding: unicode
  database: drone_test
  pool: 5
  username: postgres
  password: dz